services:
  - type: web
    name: django-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn RAG.asgi:application --host 0.0.0.0 --port 10000
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: RAG.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-db
          property: connectionString

databases:
  - name: postgres-db
