services:
  - type: web
    name: django-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: daphne RAG.asgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: RAG.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-db
          property: connectionString

databases:
  - name: postgres-db
